# Generated by Django 2.2.2 on 2019-06-28 13:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_emarsys', '0004_delete_old_and_rename_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstance',
            name='context_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='data_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
