# Generated by Django 2.2.2 on 2019-06-28 13:33

from django.db import migrations
from django.contrib.postgres.fields import JSONField
from django.db.models.functions import Cast

def move_data(apps, schema_editor):
    from django.db.models import F

    EventInstance = apps.get_model("django_emarsys", "EventInstance")
    EventInstance.objects.update(data_new=Cast(F("data"), output_field=JSONField()),
                                 context_new=Cast(F("context"), output_field=JSONField()))


class Migration(migrations.Migration):

    dependencies = [
        ('django_emarsys', '0005_auto_20190628_1331'),
    ]

    operations = [
        migrations.RunPython(move_data, migrations.RunPython.noop),
    ]
