# Generated by Django 2.2.2 on 2019-06-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_emarsys', '0006_auto_20190628_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinstance',
            name='context',
        ),
        migrations.RemoveField(
            model_name='eventinstance',
            name='data',
        ),
    ]
