# Generated by Django 2.2.2 on 2019-06-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_emarsys', '0007_auto_20190628_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinstance',
            old_name='context_new',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='eventinstance',
            old_name='data_new',
            new_name='data',
        ),
    ]
